<a href="https://colab.research.google.com/github/Brandon-Bernal-A/R/blob/main/Introduccion/Matrices_y_Factores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Se pueden **crear matrices** en R con la función 'matrix()'


In [1]:
matrix(1:9, byrow = TRUE, nrow =3)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [3]:
matrix(1:10, byrow = FALSE, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Para su construcción

El primer espacio es para los elementos, c(1, 2, 3, 4, 5, 6, 7, 8, 9)

El segundo "byrow" indica como se llenan los datos, si pones TRUE se llenan las filas primero, si pones FALSE se llenan las columnas primero

nrow indica el numero de elementos por fila o col


**Nombrar columnas y renglones**

Se pueden nombrar columnas y renglones con las funciones 'colnames(nombre mareiz)' y rownames('nombre matriz') debe ser los mismos elementos de col y renglones que tenga la matriz


In [5]:
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Construct matrix
star_wars_matrix <- matrix(c(new_hope, empire_strikes, return_jedi), nrow = 3, byrow = TRUE)

star_wars_matrix

# Vectors region and titles, used for naming
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# Name the columns with region
colnames(star_wars_matrix) <- region

# Name the rows with titles
rownames(star_wars_matrix) <- titles

# Print out star_wars_matrix
star_wars_matrix

#una forma más simple es usar 'dimnames()'


[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

**Sumar renglones y columnas**

También podemos realizar sumas de renglones y columnas, por cada una de ellas



In [10]:
rowSums(star_wars_matrix)
colSums(star_wars_matrix)

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

US   non-US 
1060.779  728.100

In [9]:
worldwide_vector <- rowSums(star_wars_matrix)
worldwide_vector

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

**combinar matriz**

'cbind' combina matrices y vectores pero por columnas

'rbind' combina pero por renglones

 Ejemplo: big_matrix <- cbind(matrix1, matrix2, vector1 ...)


In [12]:
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)
all_wars_matrix

US      non-US worldwide_vector
A New Hope              460.998 314.4  775.398         
The Empire Strikes Back 290.475 247.9  538.375         
Return of the Jedi      309.306 165.8  475.106

En R, **ls()* es una función que muestra los nombres de los objetos y conjuntos de datos que hay en el entorno de trabajo.

**Seleccionar elementos**

Para seleccionar los elementos se ponen [] separados por ',' comas

[1,5] "1" fila y "5" columnas

[,1] todos los elwmwnros de la columna 1

[1,] todos los elementos de la fila 1


Operadores de matrices

También podemos usar +,-,/,*

ejemplo 2 * my_matrix multiplica por 2 todos los elementos de la matriz

 %*% se ocupa para multiplicar matrices


**Variables categóricas**

Existen cosas llamadas factores, sirven para seleccionar confuntos de un vector, Sirve para hacer clasificaciones finitas o infinitas, la función **'factors()'** realiza este proceso y son conocidas como variables categorícas


In [13]:
sex_vector <- c("Male","Female","Female","Male","Male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector #regresara solo 'Levels: Female Male'

[1] Male   Female Female Male   Male  
Levels: Female Male

**Existen variables categoricas y nominal**

La nominal no tiene un orden implícito, es decir, ninguna palabra vale mas que otra, mientras que las ordinales sí



In [14]:
# Animals
animals_vector <- c("Elephant", "Giraffe", "Donkey", "Horse")
factor_animals_vector <- factor(animals_vector)
factor_animals_vector # al ser nominal imprime Levels: Donkey Elephant Giraffe Horse


[1] Elephant Giraffe  Donkey   Horse   
Levels: Donkey Elephant Giraffe Horse

Para poder ordenar, factor() no ordena automáticamente, agregamos 'ordenred = TRUE' para indicar que hay un orden agregamos 'levels = c("level1","level2",...)' para indicar el orden

Podemos cambiar los nombres de los niveles ocupando la función **levels()**

levels(factor_vector) <- c("name1", "name2",...)


In [16]:
# Temperature
temperature_vector <- c("High", "Low", "High","Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order = TRUE, levels = c("Low", "Medium", "High"))
factor_temperature_vector #como es ordinal imprime Levels: Low < Medium < High

[1] High   Low    High   Low    Medium
Levels: Low < Medium < High

**Sumary()**

Esta función da una vista rápida dedel contenido de una variable


In [19]:
summary(temperature_vector)

   Length     Class      Mode 
        5 character character 

In [20]:
summary(factor_temperature_vector)

Low Medium   High 
     2      1      2

Cuando los factores no tienen un orden, es dificil compararlos

por ejemplo elefante, jirafa, ... no son niveles ordenados y al intentar comparar no tiene sentido, cuando trabajamos con factores que sí tienen sentido o un orden, Sí podemos comparar

Podemos seleccionar cada nivel con [i] y usar los compradores ya conocidos

